### ISSUE TITLE
Sometimes during Import status gets set to Blocked and no matter what you do you can't change it. 

### ISSUE THREAD

**Issue by tanujonactuate** [Microsoft/Recurring-Integrations-Scheduler#21]
Sometimes during Import status gets set to Blocked and no matter what you do you can't change it. Even when status is blocked or paused sometime file gets uploaded. So behavior is not consistent enough.  I am still not able to pin point on certain things when the status get set to Blocked.

Version of RIS is 1.0.0.0
Version of D365FO - Installed product version : Microsoft Dynamics 365 for Finance and Operations, Enterprise edition (July 2017)
Installed platform version : Update10 (7.0.4641.16233)

**Comment by TomekMelissa** [comment]
Blocked trigger state means that planned execution was blocked because another instance (previous execution) of the same job is still running. Trigger will be blocked until the other trigger is finished.
See [What does BLOCKED state mean for Quartz trigger](https://stackoverflow.com/questions/25736881/what-does-blocked-state-mean-for-quartz-trigger)
