### ISSUE TITLE
Add import job form | Buttons are hided by the pause job when exception occures check box

### ISSUE THREAD

**Issue by MZade** [Microsoft/Recurring-Integrations-Scheduler#42]
### Expected behavior and actual behavior.
It seems that on the "Add import job" form, the buttons are hided by the pause job when exception occures check box:

![image](https://user-images.githubusercontent.com/19854220/39416965-5bdaffb0-4c51-11e8-9b76-7eea534ab0a2.png)

This is happening using the following resolution and the change the size of text is set to 125% (while these are recommended values by Windows in this situation):

![image](https://user-images.githubusercontent.com/19854220/39417013-ad1fb1a4-4c51-11e8-88b2-25b108e22e25.png)

![image](https://user-images.githubusercontent.com/19854220/39417066-14d2f964-4c52-11e8-8e15-96db13194ce7.png)

### Steps to reproduce the problem.
Increase the size of text i.e. in my case it happens when it is set to 125%

![image](https://user-images.githubusercontent.com/19854220/39417133-898d23ce-4c52-11e8-93f7-106ca27fdb5d.png)

**Comment by winthermichael** [comment]
I have the same issue in V2.3.0 - which becomes additional problematic when you use RIS in an Azure-environment, which do not allow you change the size of text when accessing the environment remotely. Had the same issue in V1.0.1 were I barely could see the legal entity-field.

Could the forms please be made bigger so that all fields/buttons become visible?
