### ISSUE TITLE
Data export job get paused with the following error: RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()

### ISSUE THREAD

**Issue by ChristiaanSu** [Microsoft/Recurring-Integrations-Scheduler#48]
Dynamics 365FO
Installed platform version : Update15 (7.0.4841.35259)
RIS Version 1.0.1.0

This looks similar to issue #26

Dynamics 365FO Environment was updated from platform version : Update12 (7.0.4709.41124) to platform version : Update15 (7.0.4841.35259).
After the application update all the export jobs get paused randomly with the below error

**Event log error 1**
RecurringIntegrationsScheduler.Job.Export - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()

**Event log error 2**
RecurringIntegrationsScheduler.Job.Export - One or more errors occurred.
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at RecurringIntegrationsScheduler.Job.Export.Execute(IJobExecutionContext context)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()<---

**Event log notification**
Quartz.Core.JobRunShell - Job Export jobs.  threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Export job: Export jobs.  failed ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Export.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run() [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()]

Thanks for your inputs

**Comment by TomekMelissa** [comment]
please use latest version and report back

**Comment by ChristiaanSu** [comment]
Hey Tomek,

Thanks for the quick response.
Dynamics 365FO
Installed platform version : Update15 (7.0.4841.35259)
RIS Version 2.3.0.0

Ive installed the latest version but randomly getting the following error for export jobs. This is happening for 7 different jobs thats using different data entities. Same error for all jobs.

Quartz.Core.JobRunShell - Job Export jobs. threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Export job: Export jobs. failed ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()]

**Comment by TomekMelissa** [comment]
Can you try to delete and schedule one of the job from scratch?

**Comment by ChristiaanSu** [comment]
Ive created new data projects on Dynamics and new jobs on the RIS but still getting the same error

Quartz.Core.JobRunShell - Job Export jobs.CustomerExportINTAU_CS threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Export job: Export jobs.CustomerExportINTAU_CS failed ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()]


Thanks for your inputs

**Comment by TomekMelissa** [comment]
Please add section below in RecurringIntegrationsScheduler.exe.config file
after line </configSections>
Then start Standalone scheduler and schedule one export job. Wait for it to fail and shut down RIS.
Find file network.log that should be present in RIS main folder. Send it to me directly tmelissa@microsoft.com


<system.diagnostics>  
    <sources>  
      <source name="System.Net" tracemode="includehex" maxdatasize="1024">  
        <listeners>  
          <add name="System.Net"/>  
        </listeners>  
      </source>  
      <source name="System.Net.Cache">  
        <listeners>  
          <add name="System.Net"/>  
        </listeners>  
      </source>  
      <source name="System.Net.Http">  
        <listeners>  
          <add name="System.Net"/>  
        </listeners>  
      </source>  
      <source name="System.Net.Sockets">  
        <listeners>  
          <add name="System.Net"/>  
        </listeners>  
      </source>  
      <source name="System.Net.WebSockets">  
        <listeners>  
          <add name="System.Net"/>  
        </listeners>  
      </source>  
    </sources>  
    <switches>  
      <add name="System.Net" value="Verbose"/>  
      <add name="System.Net.Cache" value="Verbose"/>  
      <add name="System.Net.Http" value="Verbose"/>  
      <add name="System.Net.Sockets" value="Verbose"/>  
      <add name="System.Net.WebSockets" value="Verbose"/>  
    </switches>  
    <sharedListeners>  
      <add name="System.Net"  
        type="System.Diagnostics.TextWriterTraceListener"  
        initializeData="network.log"  
      />  
    </sharedListeners>  
    <trace autoflush="true"/>  
  </system.diagnostics>

**Comment by ChristiaanSu** [comment]
Ive done a test using download job and not the export job.
When I use the download job I dont get the same error as when im using the export job.

**Comment by abhishekbaluni** [comment]
any resolution, the RIS keeps logging this error , but it necessarily does not mean that export has failed ?? sometimes i see the export file, and the error also being logged


Quartz.Core.JobRunShell - Job HJ Export.HJ Sales Order Export threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Export job: Export.Sales Order Export failed ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__17.MoveNext()

**Comment by TomekMelissa** [comment]
I am trying to repro that error. 
Could you guys tell me what data entities you are using? what is the volume of exported data?
Looks like this happens on GetExecutionSummaryStatus request, but I need to define more precise conditions.

**Comment by TomekMelissa** [comment]
Check v.2.4.0 It should fix this

**Comment by abhishekbaluni** [comment]
Thank you Tomek for the quick response,  i will install  this version

**Comment by ChristiaanSu** [comment]
Hi Tomek,

I installed the latest version v.2.4.0 and created export jobs with he below parameters

Recurrence: 10 mins
Status Check Interval: 120 sec
Retry policy 1:
Delay:60
Pause job when error occurs: yes

For some reason the jobs goes into a blocking state but does not release the blocking at all. It worked fine for a few hours where it went from Normal > Blocking > Normal but now its stuck in blocking.
Its been in a blocked state now for 12 hours.

Ive deleted the jobs and created them again and the same happened. 

Any help would be appreciated.

**Comment by TomekMelissa** [comment]
run it with debug mode enabled in config. Then check logs. I guess it is problem with status message again. Seems like D365 does not reliably responds with it. For few previous version the first request with ExportToPackage was actually synchronous, and then first check for status of export always responded with "Succeded". Now it is finally asynchronous operation, but sometimes all you get from D365 is "Bad request" after query about status of export job.
I decided to try 1000 times before I break the loop of status query. So 1000*2 minutes is actually over 33 hours... and all you get is bad request response probably. Need to think how to workaround this, but the main problem is reliability of D365...
Debug mode and logs should be able to verify this.

**Comment by TomekMelissa** [comment]
This is code snippet responsible for this
do
                {
                    attempt++;
                    if(attempt != 1)
                        System.Threading.Thread.Sleep(_settings.Interval);
                    executionStatus = await _httpClientHelper.GetExecutionSummaryStatus(executionId);
                    if (Log.IsDebugEnabled)
                        Log.Debug(string.Format(Resources.Job_0_Checking_if_export_is_completed_Try_1_Status_2, _context.JobDetail.Key, attempt, executionStatus));
                    if (attempt == 1000)
                        break;
                }
                while ((executionStatus == "NotRun" || executionStatus == "Executing" || executionStatus == "Bad request"));

You could argue that I should not include "Bad response" in the condition, but I saw cases when this kind of response was only random and the next request returned proper status. In your case, I guess it is permanent. Try to use 5 seconds interval. In worst scenario it will only block your job for ca. 1h 30m.

**Comment by TomekMelissa** [comment]
Please send me environment IDs of instances where you are facing this issue. Send it by email please.

**Comment by abhishekbaluni** [comment]
Hi Tomek 

any more update on this, we have started hitting this issue more frequently,sometimes  it would be an hour before a successful export ,  

Regards

**Comment by TomekMelissa** [comment]
See previous comment.

**Comment by abhishekbaluni** [comment]
thanks Tomek, totally skipped the previous comment,

**Comment by abhishekbaluni** [comment]
hi Tomek, 

an update on this , we had MS change the flag to sync instead of async,  as you had mentioned. 
past 24 hours hardly any job failure  due to the above issue 

there another error, that i havent seen before that popped up 
does the following error mean, that the dowload failed


Quartz.Core.JobRunShell - Job  Export.TestExport schedule threw a JobExecutionException: Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False  Quartz.JobExecutionException: Export job:  Export.11  Delivery schedule failed ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.Policy.<>c__DisplayClass208_0`1.<<ExecuteAsyncInternal>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.RetrySyntaxAsync.<>c__DisplayClass21_1.<<WaitAndRetryAsync>b__1>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.Policy.<ExecuteAsyncInternal>d__208`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<PostStringRequestAsync>d__10.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<ExportToPackage>d__23.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()   --- End of inner exception stack trace ---   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.Policy.<>c__DisplayClass208_0`1.<<ExecuteAsyncInternal>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.RetrySyntaxAsync.<>c__DisplayClass21_1.<<WaitAndRetryAsync>b__1>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Polly.Policy.<ExecuteAsyncInternal>d__208`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<PostStringRequestAsync>d__10.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<ExportToPackage>d__23.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()]ReplyForward |   | ReplyForward |   |  
-- | -- | -- | -- | --
  | ReplyForward

**Comment by TomekMelissa** [comment]
Is this reproducible error? What are the conditions? Looks like an error after few retries handled by Polly, but I cannot figure out what exactly is going on from this alone.

**Comment by abhishekbaluni** [comment]
it started occuring one of the export job, after MS switched  the exporttopackage call to sync,   
the project executes okay in D365, and then RIS logs this error exactly an hour later, the job starts at 2 :00 am and this error is logged at 3:00am

**Comment by TomekMelissa** [comment]
Looks like you are trying to export a lot of data and 1 hour timeout of HttpClient set in RIS is just not enough. You can increase it, but I would suggest to first evaluate why it is taking so long.
Lines 52-55 in HttpClientHelper.cs
```
_httpClient = new HttpClient(httpClientHandler)
{
    Timeout = TimeSpan.FromMinutes(60) //Timeout for large uploads or downloads
};
```
