### ISSUE TITLE
Blocked status with no execution

### ISSUE THREAD

**Issue by phillipsra16** [Microsoft/Recurring-Integrations-Scheduler#82]
When running an Export Job, the job will become Blocked, but it has not created an ExecutionId in Dynamics, nor does any log get generated.  The only way to get the trigger out of the Blocked state is to reset the RIS service.  This impacts several export jobs that we are running with frequencies varying from every 30 minutes, to daily, to weekly.  I have tried making the "Status check interval" both longer and shorter, but receive the same behavior regardless.  It does not happen every time, but with jobs running every 30 minutes, they become Blocked and "freeze" daily, if not more often.

It does not seem to behave exactly like the other issues that have been raised around "Blocked".  It is an Export, so there is no package template (even so, I remove the data files from all package templates) and it is not due to the process being long running, as the export typically happens in under 30 seconds inside of DMF.

This is on RIS version 2.6.0.  Dynamics 8.0 PU20.

**Comment by TomekMelissa** [comment]
Check event log. Look for checking status tries. Probably due to async issue RIS is unable to check export status of your package and RIS job is trying and trying to get it without success. Blocked state of a trigger means that according to RIS its job is still running. The only blocked thing is another instance of RIS job from running concurrently with the active one. 
You need to find the reason on D365 side. Contact MS support.

**Comment by TomekMelissa** [comment]
This is most likely not RIS issue, but known async export issue of D365. Ask for support for D365 not RIS. You can trace requests and responses of RIS with fiddler to find out more.
Blocked trigger status is only indication that the job is running. In your case RIS job is trying to get execution status of export job on D365 side. It receives nothing probably and stays in that state. As I said check event log to see consecutive tries that RIS is performing.
